// Generated by TASTE  (kazoo/templates/skeletons/slim-simu-body/function.tmplt)
// DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#include <stdio.h>
#include <dataview-uniq.h>

#define Engine_SIM_INTERFACE
#include <vivas_sim_interface.h>

void Engine_PI_input (const asn1SccMyInteger*const Arg)
{
	// printf("Procedure Engine_PI_input called\n");
	/** DO NOT CHANGE this lines, call to the underling hw
     * 	input
     * 	Arg : IN  asn1SccMyInteger
	**/
	sim_interface->input
(*Arg);
	// DO NOT CHANGE END
}


void Engine_PI_thrust (asn1SccMyInteger*const Arg)
{
	// printf("Procedure Engine_PI_thrust called\n");
	/** DO NOT CHANGE this lines, call to the underling hw
     * 	thrust
     * 	Arg : OUT asn1SccMyInteger
	**/
	sim_interface->thrust
(Arg);
	// DO NOT CHANGE END
}

void Engine_PI_Startup(){
    // printf("Procedure Engine_PI_Startup called\n");
}
